language: csharp
solution: Common.sln
install:
  - nuget restore Common.sln
  - nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Common.sln
  - mono ./testrunner/xunit.runners.2.4.0/tools/xunit.console.clr4.exe ./CommonLib.Tests/bin/Release/CommonLib.Tests.dll
